In [1]:
import pandas as pd
import numpy as np

In [4]:
# read a dataset into df_3rdfloor_bricks
df_3rdfloor_bricks = pd.read_csv('ParadiseView/out/df_thirdfloor_bricks.csv')

In [5]:
# display the dataset
df_3rdfloor_bricks

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cement,100.0,480.0,48000.0,2025-10-14,Brick Molding,3rd Floor,73.75
1,Cement Transport,100.0,20.0,2000.0,2025-10-14,Brick Molding,3rd Floor,73.75
2,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-14,Brick Molding,3rd Floor,73.75
3,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-15,Brick Molding,3rd Floor,73.75
4,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-17,Brick Molding,3rd Floor,73.75
5,Brick Molding Cost,2910.0,6.0,17460.0,2025-10-20,Brick Molding,3rd Floor,73.75
6,Cement,100.0,480.0,48000.0,2025-10-20,Brick Molding,3rd Floor,73.75
7,Cement Transport,100.0,20.0,2000.0,2025-10-20,Brick Molding,3rd Floor,73.75
8,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-21,Brick Molding,3rd Floor,73.75
9,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-23,Brick Molding,3rd Floor,73.75
10,Brick Molding Cost,2766.0,6.0,16600.0,2025-10-27,Brick Molding,3rd Floor,73.75
11,Cement,50.0,480.0,24000.0,2025-10-27,Brick Molding,3rd Floor,73.75
12,Cement Transport,50.0,20.0,1000.0,2025-10-27,Brick Molding,3rd Floor,73.75
13,Sand (10 Wheel),1.0,8500.0,8500.0,2025-10-27,Brick Molding,3rd Floor,73.75
14,Brick Molding Cost,1400.0,6.0,8400.0,2025-10-29,Brick Molding,3rd Floor,73.75

In [6]:
# read a csv file
df_3rdfloor_const = pd.read_csv('ParadiseView/out/df_thirdfloor_const.csv')

In [7]:
df_3rdfloor_const

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cement,36.0,480.0,17280.0,2026-12-29,Construction,3rd Floor,74.00
1,Cement Transport,36.0,20.0,720.0,2026-12-29,Construction,3rd Floor,74.00
2,Sand (10 Wheel),1.0,8000.0,8000.0,2026-12-29,Construction,3rd Floor,74.00
3,Contractor Njaye Payment,1.0,100000.0,100000.0,2026-01-20,Construction,3rd Floor,73.50
4,Iron Rod (12mm),103.0,540.0,55620.0,2026-01-22,Construction,3rd Floor,73.50
...,...,...,...,...,...,...,...,...
66,Material Transport,1.0,500.0,500.0,2026-04-11,Construction,3rd Floor,73.75
67,Big Pillar Mold Rental (days),1.0,1000.0,1000.0,2026-04-14,Construction,3rd Floor,73.75
68,Big Pillar Mold Transport,2.0,300.0,600.0,2026-04-14,Construction,3rd Floor,73.75
69,Contractor Njaye Payment,1.0,50000.0,50000.0,2026-04-20,Construction,3rd Floor,73.75
70,Residual - for Bubacarr Faye,1.0,647.0,647.0,2026-04-29,Construction,3rd Floor,73.75

In [8]:
df_3rdfloor_roof = pd.read_csv('ParadiseView/out/df_thirdfloor_roof.csv')

In [9]:
df_3rdfloor_roof

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Ali Salary,1.0,5500.0,5500.0,2026-05-01,Roof Concreting,3rd Floor,73.80
1,1/2 Wood,200.0,100.0,20000.0,2026-05-01,Roof Concreting,3rd Floor,73.80
2,1/2 Wood Transport,1.0,800.0,800.0,2026-05-01,Roof Concreting,3rd Floor,73.80
3,2/3 Wood Rentals(25Days),150.0,5.5,20625.0,2026-05-01,Roof Concreting,3rd Floor,73.80
4,2/3 Woods Transport,1.0,1000.0,1000.0,2026-05-01,Roof Concreting,3rd Floor,73.80
...,...,...,...,...,...,...,...,...
72,Cement,3.0,455.0,1365.0,2026-05-22,Roof Concreting,3rd Floor,73.75
73,Cement Transport,3.0,20.0,60.0,2026-05-22,Roof Concreting,3rd Floor,73.75
74,Access- no Change for Bubacarr Faye,1.0,40.0,40.0,2026-06-11,Roof Concreting,3rd Floor,74.00
75,Rebuilding the Fence,1.0,2500.0,2500.0,2026-06-14,Roof Concreting,3rd Floor,74.00
76,Ali Watering the Roof,1.0,2000.0,2000.0,2026-07-03,Roof Concreting,3rd Floor,74.00

In [10]:
df_3rdfloor_bricks.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           15 non-null     str
 1   quantity       15 non-null     float64
 2   unit_cost      15 non-null     float64
 3   total_cost     15 non-null     float64
 4   date           15 non-null     str
 5   sub_category   15 non-null     str
 6   category       15 non-null     str
 7   exchange_rate  15 non-null     float64
dtypes: float64(4), str(4)
memory usage: 1.1 KB

In [11]:
df_3rdfloor_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           71 non-null     str
 1   quantity       71 non-null     float64
 2   unit_cost      71 non-null     float64
 3   total_cost     71 non-null     float64
 4   date           71 non-null     str
 5   sub_category   71 non-null     str
 6   category       71 non-null     str
 7   exchange_rate  71 non-null     float64
dtypes: float64(4), str(4)
memory usage: 4.6 KB

In [12]:
df_3rdfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           77 non-null     str
 1   quantity       77 non-null     float64
 2   unit_cost      77 non-null     float64
 3   total_cost     77 non-null     float64
 4   date           77 non-null     str
 5   sub_category   77 non-null     str
 6   category       77 non-null     str
 7   exchange_rate  77 non-null     float64
dtypes: float64(4), str(4)
memory usage: 4.9 KB

In [13]:
# combine the dataset together
thirdfloor = pd.concat([df_3rdfloor_bricks, df_3rdfloor_const, df_3rdfloor_roof], ignore_index=True)

In [14]:
print(thirdfloor.to_string())

                                           item  quantity  unit_cost  total_cost        date     sub_category   category  exchange_rate
0                                       Cement      100.0      480.0     48000.0  2025-10-14    Brick Molding  3rd Floor          73.75
1                              Cement Transport     100.0       20.0      2000.0  2025-10-14    Brick Molding  3rd Floor          73.75
2                               Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-14    Brick Molding  3rd Floor          73.75
3                               Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-15    Brick Molding  3rd Floor          73.75
4                               Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-17    Brick Molding  3rd Floor          73.75
5                            Brick Molding Cost    2910.0        6.0     17460.0  2025-10-20    Brick Molding  3rd Floor          73.75
6                                       Cement      100.0      480.0     48000.0  2025-10-20    Brick Molding  3rd Floor          73.75
7                              Cement Transport     100.0       20.0      2000.0  2025-10-20    Brick Molding  3rd Floor          73.75
8                               Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-21    Brick Molding  3rd Floor          73.75
9                               Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-23    Brick Molding  3rd Floor          73.75
10                           Brick Molding Cost    2766.0        6.0     16600.0  2025-10-27    Brick Molding  3rd Floor          73.75
11                                      Cement       50.0      480.0     24000.0  2025-10-27    Brick Molding  3rd Floor          73.75
12                             Cement Transport      50.0       20.0      1000.0  2025-10-27    Brick Molding  3rd Floor          73.75
13                              Sand (10 Wheel)       1.0     8500.0      8500.0  2025-10-27    Brick Molding  3rd Floor          73.75
14                           Brick Molding Cost    1400.0        6.0      8400.0  2025-10-29    Brick Molding  3rd Floor          73.75
15                                       Cement      36.0      480.0     17280.0  2026-12-29     Construction  3rd Floor          74.00
16                            Cement Transport       36.0       20.0       720.0  2026-12-29     Construction  3rd Floor          74.00
17                              Sand (10 Wheel)       1.0     8000.0      8000.0  2026-12-29     Construction  3rd Floor          74.00
18                     Contractor Njaye Payment       1.0   100000.0    100000.0  2026-01-20     Construction  3rd Floor          73.50
19                              Iron Rod (12mm)     103.0      540.0     55620.0  2026-01-22     Construction  3rd Floor          73.50
20                                 Binding Wire       1.0      500.0       500.0  2026-01-22     Construction  3rd Floor          73.50
21           Iron Rod + Binding Wite Transport        1.0      700.0       700.0  2026-01-22     Construction  3rd Floor          73.50
22                          Big Plastic Barrel        2.0     1000.0      2000.0  2026-01-23     Construction  3rd Floor          73.50
23                           Barrels Transport        1.0      500.0       500.0  2026-01-23     Construction  3rd Floor          73.50
24                           Gas for Generator        1.0      475.0       475.0  2026-01-23     Construction  3rd Floor          73.50
25                        Bubacarr Faye Payment       1.0    60000.0     60000.0  2026-01-24     Construction  3rd Floor          73.50
26                                       Cement     100.0      465.0     46500.0  2026-01-27     Construction  3rd Floor          73.75
27                            Cement Transport      100.0       20.0      2000.0  2026-01-27     Construction  3rd Floor          73.75
28                              Sand (10 Wheel)       1.0     8000.0      8000.0  2026-01-27     Construction  3rd Floor          73.75
29                     Contractor Njaye Payment       1.0   100000.0    100000.0  2026-01-28     Construction  3rd Floor          73.75
30                      Fixing Momo Haja’s Gate       1.0      700.0       700.0  2026-01-29     Construction  3rd Floor          73.75
31                           Gas for Generator        1.0      500.0       500.0  2026-01-30     Construction  3rd Floor          73.75
32                               Asphalt (95cu)       1.0    95000.0     95000.0  2026-01-31     Construction  3rd Floor          73.75
33                                    Nail (kg)      10.0      100.0      1000.0  2026-01-31     Construction  3rd Floor          73.75
34                                Ali’ Payment        1.0     5500.0      5500.0  2026-02-04     Construction  3rd Floor          73.75
35                     Generator Repair and Gas       1.0     1250.0      1250.0  2026-02-07     Construction  3rd Floor          73.75
36                              Iron Rod (10mm)     250.0      330.0     82500.0  2026-02-08     Construction  3rd Floor          73.75
37                               Iron Rod (6mm)     200.0      130.0     26000.0  2026-02-08     Construction  3rd Floor          73.75
38                                 Binding Wire       3.0      500.0      1500.0  2026-02-08     Construction  3rd Floor          73.75
39                          Materials Transport       1.0     1800.0      1800.0  2026-02-08     Construction  3rd Floor          73.75
40                     Contractor Njaye Payment       1.0   100000.0    100000.0  2026-02-09     Construction  3rd Floor          73.75
41                        Ali Packing the Woods       1.0     2000.0      2000.0  2026-02-09     Construction  3rd Floor          73.75
42                                    Nail (kg)       7.0      101.0       707.0  2026-02-12     Construction  3rd Floor          73.75
43                              Sand (10 Wheel)       1.0     8000.0      8000.0  2026-02-13     Construction  3rd Floor          73.75
44                     Generator Repair and Gas       1.0     1900.0      1900.0  2026-02-14     Construction  3rd Floor          73.75
45                                       Cement      50.0      450.0     22500.0  2026-02-18     Construction  3rd Floor          73.75
46                            Cement Transport       50.0       20.0      1000.0  2026-02-18     Construction  3rd Floor          73.75
47                                     2/5 Wood       4.0      325.0      1300.0  2026-02-18     Construction  3rd Floor          73.75
48                          1/5 Wood Transport        4.0      100.0       400.0  2026-02-18     Construction  3rd Floor          73.75
49                           Gas for Generator        1.0      450.0       450.0  2026-02-21     Construction  3rd Floor          73.75
50                         Ramadan Experiences        1.0     6000.0      6000.0  2026-03-26     Construction  3rd Floor          73.75
51                                    Nail (kg)       9.0      100.0       900.0  2026-03-02     Construction  3rd Floor          73.75
52                                     1/2 Wood      15.0      120.0      1800.0  2026-03-02     Construction  3rd Floor          73.75
53                          Materials Transport       1.0      300.0       300.0  2026-03-02     Construction  3rd Floor          73.75
54                                       Cement      50.0      450.0     22500.0  2026-03-03     Construction  3rd Floor          73.75
55                            Cement Transport       50.0       22.0      1100.0  2026-03-03     Construction  3rd Floor          73.75
56                              Sand (10 Wheel)       1.0     8000.0      8000.0  2026-03-03     Construction  3rd Floor          73.75
57                           Gas for Generator        1.0      400.0       400.0  2026-03-06     Construction  3rd Floor          73.75
58                                 Ali’ Salary        1.0     5500.0      5500.0  2026-03-06     Construction  3rd Floor          73.75
59                                       Cement      25.0      450.0     11250.0  2026-03-13     Construction  3rd Floor          73.75
60                            Cement Transport       25.0       20.0       500.0  2026-03-13     Construction  3rd Floor          73.75
61                           Gas for Generator        1.0      400.0       400.0  2026-03-13     Construction  3rd Floor          73.75
62                              Design Pillars        6.0     1500.0      9000.0  2026-03-15     Construction  3rd Floor          73.75
63                     Contractor Njaye Payment       1.0    20000.0     20000.0  2026-03-17     Construction  3rd Floor          73.75
64                          Oil for Big Pillars       1.0      140.0       140.0  2026-03-17     Construction  3rd Floor          73.75
65                                       Cement      25.0      450.0     11250.0  2026-03-17     Construction  3rd Floor          73.75
66                            Cement Transport       25.0       20.0       500.0  2026-03-17     Construction  3rd Floor          73.75
67               Big Pillar Mold  Rental (days)       3.0     1000.0      3000.0  2026-03-19     Construction  3rd Floor          73.75
68                   Big Pillar Mold Transport        1.0     1000.0      1000.0  2026-03-19     Construction  3rd Floor          73.75
69                         Cardboard and nails        1.0      700.0       700.0  2026-03-26     Construction  3rd Floor          73.75
70                                    1/5 Wood        5.0      350.0      1750.0  2026-03-28     Construction  3rd Floor          73.75
71                          1/5 Wood Transport        1.0      400.0       400.0  2026-03-28     Construction  3rd Floor          73.75
72                           Gas for Generator        1.0      400.0       400.0  2026-03-28     Construction  3rd Floor          73.75
73                Bubacarr Faye Court Expenses        1.0     1000.0      1000.0  2026-03-29     Construction  3rd Floor          73.75
74             Scaffolding Rental, Safo (Daily)       6.0      150.0       900.0  2026-03-30     Construction  3rd Floor          73.75
75                        Scaffolding Transport       2.0      200.0       400.0  2026-03-30     Construction  3rd Floor          73.75
76                                    Nail (kg)       2.0      100.0       200.0  2026-03-30     Construction  3rd Floor          73.75
77                                 Ali’ Salary        1.0     5500.0      5500.0  2026-04-01     Construction  3rd Floor          73.75
78                              Acrojack Rental       6.0       25.0       150.0  2026-04-11     Construction  3rd Floor          73.75
79             Scaffolding Rental, Safo (Daily)       1.0     1200.0      1200.0  2026-04-11     Construction  3rd Floor          73.75
80                                     1/2 Wood       2.0      120.0       240.0  2026-04-11     Construction  3rd Floor          73.75
81                          Material Transport        1.0      500.0       500.0  2026-04-11     Construction  3rd Floor          73.75
82               Big Pillar Mold  Rental (days)       1.0     1000.0      1000.0  2026-04-14     Construction  3rd Floor          73.75
83                   Big Pillar Mold Transport        2.0      300.0       600.0  2026-04-14     Construction  3rd Floor          73.75
84                     Contractor Njaye Payment       1.0    50000.0     50000.0  2026-04-20     Construction  3rd Floor          73.75
85                 Residual - for Bubacarr Faye       1.0      647.0       647.0  2026-04-29     Construction  3rd Floor          73.75
86                                  Ali Salary        1.0     5500.0      5500.0  2026-05-01  Roof Concreting  3rd Floor          73.80
87                                     1/2 Wood     200.0      100.0     20000.0  2026-05-01  Roof Concreting  3rd Floor          73.80
88                          1/2 Wood Transport        1.0      800.0       800.0  2026-05-01  Roof Concreting  3rd Floor          73.80
89                     2/3 Wood Rentals(25Days)     150.0        5.5     20625.0  2026-05-01  Roof Concreting  3rd Floor          73.80
90                          2/3 Woods Transport       1.0     1000.0      1000.0  2026-05-01  Roof Concreting  3rd Floor          73.80
91                                    Nail(Box)       3.0     2500.0      7500.0  2026-05-01  Roof Concreting  3rd Floor          73.80
92                        Concrete Nail(BigBox)       1.0     1500.0      1500.0  2026-05-01  Roof Concreting  3rd Floor          73.80
93                                   Carpenter        1.0    30000.0     30000.0  2026-05-02  Roof Concreting  3rd Floor          73.80
94                           Gas for Generator        1.0      400.0       400.0  2026-05-06  Roof Concreting  3rd Floor          73.80
95                     AcroJack Rentals(18Days)     250.0        2.5     11250.0  2026-05-08  Roof Concreting  3rd Floor          73.80
96                          AcroJack Transport        1.0     1500.0      1500.0  2026-05-08  Roof Concreting  3rd Floor          73.80
97                     2/3 Wood Rentals(17Days)     120.0        5.0     10200.0  2026-05-09  Roof Concreting  3rd Floor          73.80
98                          2/3 Woods Transport       1.0     1200.0      1200.0  2026-05-09  Roof Concreting  3rd Floor          73.80
99                             Plywood (15Days)      65.0       19.0     18525.0  2026-05-11  Roof Concreting  3rd Floor          73.80
100                    AcroJack Rentals(25Days)     150.0        2.5      9375.0  2026-05-11  Roof Concreting  3rd Floor          73.80
101             AcroJack and Plywood Transport        1.0     3000.0      3000.0  2026-05-11  Roof Concreting  3rd Floor          73.80
102                    2/3 Wood Rentals(16Days)      50.0        5.0      4000.0  2026-05-11  Roof Concreting  3rd Floor          73.80
103                         2/3 Woods Transport       1.0      600.0       600.0  2026-05-11  Roof Concreting  3rd Floor          73.80
104                      Brick Molding (5 Bags)     155.0        6.0      1100.0  2026-05-13  Roof Concreting  3rd Floor          73.80
105                                  Carpenter        1.0    15000.0     15000.0  2026-05-16  Roof Concreting  3rd Floor          73.75
106                              Iron Rod(12mm)      40.0      525.0     21000.0  2026-05-16  Roof Concreting  3rd Floor          73.75
107                              Iron Rod(10mm)     500.0      330.0    165000.0  2026-05-16  Roof Concreting  3rd Floor          73.75
108                                Binding Wire       3.0      500.0      1500.0  2026-05-16  Roof Concreting  3rd Floor          73.75
109                        Iron Rods Transport        1.0     3300.0      3300.0  2026-05-16  Roof Concreting  3rd Floor          73.75
110                            Iron Man Payment       1.0    20000.0     20000.0  2026-05-17  Roof Concreting  3rd Floor          73.75
111                                Plywood 12mm      11.0     1750.0     19250.0  2026-05-18  Roof Concreting  3rd Floor          73.85
112                                Plywood 12mm      10.0     1800.0     18000.0  2026-05-18  Roof Concreting  3rd Floor          73.85
113                                    2/3 Wood      25.0      250.0      6250.0  2026-05-18  Roof Concreting  3rd Floor          73.85
114                                    1/6 Wood      15.0      340.0      5100.0  2026-05-18  Roof Concreting  3rd Floor          73.85
115                        Concrete Nail (Pack)      10.0       35.0       350.0  2026-05-18  Roof Concreting  3rd Floor          73.85
116                                      Cement       1.0      475.0       475.0  2026-05-18  Roof Concreting  3rd Floor          73.85
117                        Materials Transport        1.0     1500.0      1500.0  2026-05-18  Roof Concreting  3rd Floor          73.85
118                              Asphalt(19cu)        1.0   100000.0    100000.0  2026-05-18  Roof Concreting  3rd Floor          73.85
119             Ali Moving the Neighbor’s Sand        1.0     2200.0      2200.0  2026-05-19  Roof Concreting  3rd Floor          73.85
120                          Plumbing Materials       1.0    19000.0     19000.0  2026-05-19  Roof Concreting  3rd Floor          73.85
121                        Electrical Materials       1.0    13325.0     13325.0  2026-05-19  Roof Concreting  3rd Floor          73.85
122  Plumbing & Electrical Materials Transport        1.0      600.0       600.0  2026-05-19  Roof Concreting  3rd Floor          73.85
123                                    Plumber        1.0    10000.0     10000.0  2026-05-20  Roof Concreting  3rd Floor          73.85
124                                Electrician        1.0     9000.0      9000.0  2026-05-19  Roof Concreting  3rd Floor          73.85
125                                Washed Stone       3.0    15500.0     46500.0  2026-05-19  Roof Concreting  3rd Floor          73.85
126                                        Sand       3.0     9000.0     27000.0  2026-05-21  Roof Concreting  3rd Floor          73.75
127                          Gas for Generator        1.0      400.0       400.0  2026-05-21  Roof Concreting  3rd Floor          73.75
128                                Binding Wire       1.0      500.0       500.0  2026-05-21  Roof Concreting  3rd Floor          73.75
129                         Plumbing Materials        1.0      200.0       200.0  2026-05-21  Roof Concreting  3rd Floor          73.75
130                               Plumber Extra       1.0     2000.0      2000.0  2026-05-21  Roof Concreting  3rd Floor          73.75
131                                      Cement     343.0      455.0    156065.0  2026-05-22  Roof Concreting  3rd Floor          73.75
132                           Cement Transport      343.0       20.0      6860.0  2026-05-22  Roof Concreting  3rd Floor          73.75
133                          Gas for Generator        1.0     1100.0      1100.0  2026-05-22  Roof Concreting  3rd Floor          73.75
134                        Electrical Materials       1.0      200.0       200.0  2026-05-22  Roof Concreting  3rd Floor          73.75
135                                    Acrojack      16.0        3.0      1000.0  2026-05-22  Roof Concreting  3rd Floor          73.75
136                            Iron Man Payment       1.0    15000.0     15000.0  2026-05-22  Roof Concreting  3rd Floor          73.75
137                      Iron Man Extra Payment       1.0     3000.0      3000.0  2026-05-22  Roof Concreting  3rd Floor          73.75
138                                    2/8 Wood       5.0      700.0      3500.0  2026-05-22  Roof Concreting  3rd Floor          73.75
139                         2/8 Wood Transport        1.0      400.0       400.0  2026-05-22  Roof Concreting  3rd Floor          73.75
140                                Concrete Man       1.0    45000.0     45000.0  2026-05-23  Roof Concreting  3rd Floor          73.75
141                         Concrete Guys Lunch       1.0     2000.0      2000.0  2026-05-23  Roof Concreting  3rd Floor          73.75
142                      Supervising Contractor       1.0     1500.0      1500.0  2026-05-23  Roof Concreting  3rd Floor          73.75
143                          Gas for Generator        1.0     1000.0      1000.0  2026-05-25  Roof Concreting  3rd Floor          73.75
144                Ali Transporting the Cement        1.0     1000.0      1000.0  2026-05-26  Roof Concreting  3rd Floor          73.75
145                           Carpenter Payment       1.0     5000.0      5000.0  2026-05-26  Roof Concreting  3rd Floor          73.75

In [15]:
# get quick overview of the dataset
thirdfloor.info()

<class 'pandas.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           163 non-null    str
 1   quantity       163 non-null    float64
 2   unit_cost      163 non-null    float64
 3   total_cost     163 non-null    float64
 4   date           163 non-null    str
 5   sub_category   163 non-null    str
 6   category       163 non-null    str
 7   exchange_rate  163 non-null    float64
dtypes: float64(4), str(4)
memory usage: 10.3 KB

In [17]:
# save the dataset as a csv file
thirdfloor.to_csv('Paradiseview/clean/floorThree.csv', index=False)