In [1]:
import pandas as pd
import numpy as np

In [2]:
thirdfloor_roof = pd.read_excel('para/Paradise View.xlsx', sheet_name='3rd Floor Roof Concrete ', skiprows=1)

In [3]:
thirdfloor_roof

,ITEM,QUALITY,UNIT PRICE(D),TOTAL COST(D),DATE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Ali Salary,1.0,5500.0,5500.0,2026-05-01,NaN,NaN,NaN,NaN,NaN,NaN
1,1/2 Wood,200.0,100.0,20000.0,2029-05-01,NaN,NaN,NaN,NaN,NaN,NaN
2,1/2 Wood Transport,1.0,800.0,800.0,2026-05-01,NaN,NaN,NaN,NaN,NaN,NaN
3,2/3 Wood Rentals(25Days),150.0,5.5,20625.0,2026-05-01,NaN,NaN,NaN,NaN,NaN,NaN
4,2/3 Woods Transport,1.0,1000.0,1000.0,2026-05-01,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
97,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaT,NaN,TOTAL SPENT,NaN,1028740,NaN,NaN
100,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaT,NaN,TOTAL REMAINING,NaN,11600,NaN,NaN

In [4]:
thirdfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ITEM           77 non-null     str
 1   QUALITY        76 non-null     float64
 2   UNIT PRICE(D)  76 non-null     float64
 3   TOTAL COST(D)  77 non-null     float64
 4   DATE           76 non-null     datetime64[us]
 5   Unnamed: 5     0 non-null      float64
 6   Unnamed: 6     12 non-null     str
 7   Unnamed: 7     8 non-null      object
 8   Unnamed: 8     11 non-null     object
 9   Unnamed: 9     8 non-null      object
 10  Unnamed: 10    7 non-null      object
dtypes: datetime64[us](1), float64(4), object(4), str(2)
memory usage: 8.9+ KB

In [5]:
thirdfloor_roof.dropna(how='all', axis=1, inplace=True)

In [6]:
thirdfloor_roof

,ITEM,QUALITY,UNIT PRICE(D),TOTAL COST(D),DATE,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Ali Salary,1.0,5500.0,5500.0,2026-05-01,NaN,NaN,NaN,NaN,NaN
1,1/2 Wood,200.0,100.0,20000.0,2029-05-01,NaN,NaN,NaN,NaN,NaN
2,1/2 Wood Transport,1.0,800.0,800.0,2026-05-01,NaN,NaN,NaN,NaN,NaN
3,2/3 Wood Rentals(25Days),150.0,5.5,20625.0,2026-05-01,NaN,NaN,NaN,NaN,NaN
4,2/3 Woods Transport,1.0,1000.0,1000.0,2026-05-01,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
97,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaT,TOTAL SPENT,NaN,1028740,NaN,NaN
100,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaT,TOTAL REMAINING,NaN,11600,NaN,NaN

In [7]:
thirdfloor_roof = thirdfloor_roof.drop(columns=thirdfloor_roof.loc[:, 'Unnamed: 6' : 'Unnamed: 10'].columns)

In [8]:
thirdfloor_roof.dropna(thresh=3, axis=0, inplace=True)

In [9]:
thirdfloor_roof.info()

<class 'pandas.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ITEM           76 non-null     str
 1   QUALITY        76 non-null     float64
 2   UNIT PRICE(D)  76 non-null     float64
 3   TOTAL COST(D)  76 non-null     float64
 4   DATE           76 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 3.1 KB

In [10]:
thirdfloor_roof.columns = thirdfloor_roof.columns.str.lower()

In [11]:
thirdfloor_roof.columns

Index(['item', 'quality ', 'unit price(d)', 'total cost(d)', 'date'], dtype='str')

In [12]:
thirdfloor_roof.rename(columns={'quality ': 'quantity', 'unit price(d)': 'unit_cost', 'total cost(d)': 'total_cost'}, inplace=True)

In [13]:
thirdfloor_roof['sub_category'] = 'Roof Concreting'
thirdfloor_roof['category'] = '3rd Floor'

In [14]:
thirdfloor_roof.loc[1, 'date'] = pd.to_datetime('2026-05-01')

In [15]:
thirdfloor_roof['exchange_rate'] = np.where(thirdfloor_roof['date'].between('2026-04-29', '2026-05-15'), 73.80, 0)

In [16]:
thirdfloor_roof['exchange_rate'] = np.where(thirdfloor_roof['date'].between('2026-05-16', '2026-05-17'), 73.75, thirdfloor_roof['exchange_rate'])

In [17]:
thirdfloor_roof['exchange_rate'] = np.where(thirdfloor_roof['date'].between('2026-05-18', '2026-05-20'), 73.85, thirdfloor_roof['exchange_rate'])

In [18]:
thirdfloor_roof['exchange_rate'] = np.where(thirdfloor_roof['date'].between('2026-05-21', '2026-06-10'), 73.75, thirdfloor_roof['exchange_rate'])

In [19]:
thirdfloor_roof['exchange_rate'] = np.where(thirdfloor_roof['date'].between('2026-06-11', '2026-06-16'), 74.00, thirdfloor_roof['exchange_rate'])

In [20]:
thirdfloor_roof.loc[len(thirdfloor_roof)] = ['Ali Watering the Roof', 1, 2000, 2000, pd.to_datetime('2026-07-03'), 'Roof Concreting', '3rd Floor', 74.00]

In [21]:
print(thirdfloor_roof.to_string())

                                          item  quantity  unit_cost  total_cost       date     sub_category   category  exchange_rate
0                                  Ali Salary        1.0     5500.0      5500.0 2026-05-01  Roof Concreting  3rd Floor          73.80
1                                     1/2 Wood     200.0      100.0     20000.0 2026-05-01  Roof Concreting  3rd Floor          73.80
2                          1/2 Wood Transport        1.0      800.0       800.0 2026-05-01  Roof Concreting  3rd Floor          73.80
3                     2/3 Wood Rentals(25Days)     150.0        5.5     20625.0 2026-05-01  Roof Concreting  3rd Floor          73.80
4                          2/3 Woods Transport       1.0     1000.0      1000.0 2026-05-01  Roof Concreting  3rd Floor          73.80
5                                    Nail(Box)       3.0     2500.0      7500.0 2026-05-01  Roof Concreting  3rd Floor          73.80
6                        Concrete Nail(BigBox)       1.0     1500.0      1500.0 2026-05-01  Roof Concreting  3rd Floor          73.80
7                                   Carpenter        1.0    30000.0     30000.0 2026-05-02  Roof Concreting  3rd Floor          73.80
8                           Gas for Generator        1.0      400.0       400.0 2026-05-06  Roof Concreting  3rd Floor          73.80
9                     AcroJack Rentals(18Days)     250.0        2.5     11250.0 2026-05-08  Roof Concreting  3rd Floor          73.80
10                         AcroJack Transport        1.0     1500.0      1500.0 2026-05-08  Roof Concreting  3rd Floor          73.80
11                    2/3 Wood Rentals(17Days)     120.0        5.0     10200.0 2026-05-09  Roof Concreting  3rd Floor          73.80
12                         2/3 Woods Transport       1.0     1200.0      1200.0 2026-05-09  Roof Concreting  3rd Floor          73.80
13                            Plywood (15Days)      65.0       19.0     18525.0 2026-05-11  Roof Concreting  3rd Floor          73.80
14                    AcroJack Rentals(25Days)     150.0        2.5      9375.0 2026-05-11  Roof Concreting  3rd Floor          73.80
15             AcroJack and Plywood Transport        1.0     3000.0      3000.0 2026-05-11  Roof Concreting  3rd Floor          73.80
16                    2/3 Wood Rentals(16Days)      50.0        5.0      4000.0 2026-05-11  Roof Concreting  3rd Floor          73.80
17                         2/3 Woods Transport       1.0      600.0       600.0 2026-05-11  Roof Concreting  3rd Floor          73.80
18                      Brick Molding (5 Bags)     155.0        6.0      1100.0 2026-05-13  Roof Concreting  3rd Floor          73.80
19                                  Carpenter        1.0    15000.0     15000.0 2026-05-16  Roof Concreting  3rd Floor          73.75
20                              Iron Rod(12mm)      40.0      525.0     21000.0 2026-05-16  Roof Concreting  3rd Floor          73.75
21                              Iron Rod(10mm)     500.0      330.0    165000.0 2026-05-16  Roof Concreting  3rd Floor          73.75
22                                Binding Wire       3.0      500.0      1500.0 2026-05-16  Roof Concreting  3rd Floor          73.75
23                        Iron Rods Transport        1.0     3300.0      3300.0 2026-05-16  Roof Concreting  3rd Floor          73.75
24                            Iron Man Payment       1.0    20000.0     20000.0 2026-05-17  Roof Concreting  3rd Floor          73.75
25                                Plywood 12mm      11.0     1750.0     19250.0 2026-05-18  Roof Concreting  3rd Floor          73.85
26                                Plywood 12mm      10.0     1800.0     18000.0 2026-05-18  Roof Concreting  3rd Floor          73.85
27                                    2/3 Wood      25.0      250.0      6250.0 2026-05-18  Roof Concreting  3rd Floor          73.85
28                                    1/6 Wood      15.0      340.0      5100.0 2026-05-18  Roof Concreting  3rd Floor          73.85
29                        Concrete Nail (Pack)      10.0       35.0       350.0 2026-05-18  Roof Concreting  3rd Floor          73.85
30                                      Cement       1.0      475.0       475.0 2026-05-18  Roof Concreting  3rd Floor          73.85
31                        Materials Transport        1.0     1500.0      1500.0 2026-05-18  Roof Concreting  3rd Floor          73.85
32                              Asphalt(19cu)        1.0   100000.0    100000.0 2026-05-18  Roof Concreting  3rd Floor          73.85
33             Ali Moving the Neighbor’s Sand        1.0     2200.0      2200.0 2026-05-19  Roof Concreting  3rd Floor          73.85
34                          Plumbing Materials       1.0    19000.0     19000.0 2026-05-19  Roof Concreting  3rd Floor          73.85
35                        Electrical Materials       1.0    13325.0     13325.0 2026-05-19  Roof Concreting  3rd Floor          73.85
36  Plumbing & Electrical Materials Transport        1.0      600.0       600.0 2026-05-19  Roof Concreting  3rd Floor          73.85
37                                    Plumber        1.0    10000.0     10000.0 2026-05-20  Roof Concreting  3rd Floor          73.85
38                                Electrician        1.0     9000.0      9000.0 2026-05-19  Roof Concreting  3rd Floor          73.85
39                                Washed Stone       3.0    15500.0     46500.0 2026-05-19  Roof Concreting  3rd Floor          73.85
40                                        Sand       3.0     9000.0     27000.0 2026-05-21  Roof Concreting  3rd Floor          73.75
41                          Gas for Generator        1.0      400.0       400.0 2026-05-21  Roof Concreting  3rd Floor          73.75
42                                Binding Wire       1.0      500.0       500.0 2026-05-21  Roof Concreting  3rd Floor          73.75
43                         Plumbing Materials        1.0      200.0       200.0 2026-05-21  Roof Concreting  3rd Floor          73.75
44                               Plumber Extra       1.0     2000.0      2000.0 2026-05-21  Roof Concreting  3rd Floor          73.75
45                                      Cement     343.0      455.0    156065.0 2026-05-22  Roof Concreting  3rd Floor          73.75
46                           Cement Transport      343.0       20.0      6860.0 2026-05-22  Roof Concreting  3rd Floor          73.75
47                          Gas for Generator        1.0     1100.0      1100.0 2026-05-22  Roof Concreting  3rd Floor          73.75
48                        Electrical Materials       1.0      200.0       200.0 2026-05-22  Roof Concreting  3rd Floor          73.75
49                                    Acrojack      16.0        3.0      1000.0 2026-05-22  Roof Concreting  3rd Floor          73.75
50                            Iron Man Payment       1.0    15000.0     15000.0 2026-05-22  Roof Concreting  3rd Floor          73.75
51                      Iron Man Extra Payment       1.0     3000.0      3000.0 2026-05-22  Roof Concreting  3rd Floor          73.75
52                                    2/8 Wood       5.0      700.0      3500.0 2026-05-22  Roof Concreting  3rd Floor          73.75
53                         2/8 Wood Transport        1.0      400.0       400.0 2026-05-22  Roof Concreting  3rd Floor          73.75
54                                Concrete Man       1.0    45000.0     45000.0 2026-05-23  Roof Concreting  3rd Floor          73.75
55                         Concrete Guys Lunch       1.0     2000.0      2000.0 2026-05-23  Roof Concreting  3rd Floor          73.75
56                      Supervising Contractor       1.0     1500.0      1500.0 2026-05-23  Roof Concreting  3rd Floor          73.75
57                          Gas for Generator        1.0     1000.0      1000.0 2026-05-25  Roof Concreting  3rd Floor          73.75
58                Ali Transporting the Cement        1.0     1000.0      1000.0 2026-05-26  Roof Concreting  3rd Floor          73.75
59                           Carpenter Payment       1.0     5000.0      5000.0 2026-05-26  Roof Concreting  3rd Floor          73.75
60                                 Wood Rental      35.0       35.0      4900.0 2026-05-26  Roof Concreting  3rd Floor          73.75
61                             Wood Transport        1.0      800.0       800.0 2026-05-26  Roof Concreting  3rd Floor          73.75
62                                 Ali Salary        1.0     5500.0      5500.0 2026-06-01  Roof Concreting  3rd Floor          73.75
63       2/3 Wood Rentals Extension ( 14 Days)     150.0        5.5     11550.0 2026-06-11  Roof Concreting  3rd Floor          74.00
64         Acrojack Rental Extension (14 Days)     250.0        2.5      8750.0 2026-06-11  Roof Concreting  3rd Floor          74.00
65                Acrojack Extension ( 3 Days)     150.0        2.5      1125.0 2026-06-11  Roof Concreting  3rd Floor          74.00
66              Plywood 12mm Rental Extension       65.0       20.0     18200.0 2026-06-11  Roof Concreting  3rd Floor          74.00
67   2/3 Wood Wood Rental Extension ( 14 Days)     170.0        5.0     11900.0 2026-06-11  Roof Concreting  3rd Floor          74.00
68                         Acrojack Transport        1.0      800.0       800.0 2026-06-11  Roof Concreting  3rd Floor          74.00
69                         Acrojack Transport        1.0     4500.0      4500.0 2026-06-11  Roof Concreting  3rd Floor          74.00
70                    Plywood & 2/3 Transport        1.0     4200.0      4200.0 2026-06-11  Roof Concreting  3rd Floor          74.00
71                           Carpenter Payment       1.0     5000.0      5000.0 2026-06-11  Roof Concreting  3rd Floor          74.00
72                                     Cement        3.0      455.0      1365.0 2026-05-22  Roof Concreting  3rd Floor          73.75
73                           Cement Transport        3.0       20.0        60.0 2026-05-22  Roof Concreting  3rd Floor          73.75
74         Access- no Change for Bubacarr Faye       1.0       40.0        40.0 2026-06-11  Roof Concreting  3rd Floor          74.00
75                        Rebuilding the Fence       1.0     2500.0      2500.0 2026-06-14  Roof Concreting  3rd Floor          74.00
76                       Ali Watering the Roof       1.0     2000.0      2000.0 2026-07-03  Roof Concreting  3rd Floor          74.00

In [7]:
thirdfloor_roof.to_csv('ParadiseView/out/df_thirdfloor_roof.csv', index=False)

In [2]:
thirdfloor_roof  = pd.read_csv('ParadiseView/out/df_thirdfloor_roof.csv')