In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('ParadiseView/out/df_cost_clean.csv')

In [4]:
df

                             item    cost        date
0   Paradise View Plot: 20m x 25m  750000  08/03/2019
1                 Physical Plan 1    1500  08/09/2019
2                 Physical Plan 2    1000  12/17/2019
3                    MoneyTra Fee     490  02/06/2020
4                 Physical Plan 2    2000  02/07/2020
5                      GTBank Fee    5000  02/07/2020
6                     Gas for Car     500  02/07/2020
7             Chief Area Council     2000  02/10/2020
8                     Gas for Car     500  02/10/2020
9               Lady Filled Forms     400  02/10/2020
10                  Sukuta Alkalo    1500  02/11/2020
11                            Gas     100  02/11/2020

In [5]:
df.columns

Index(['item', 'cost', 'date'], dtype='str')

In [7]:
df.rename(columns={'cost': 'total_cost'}, inplace=True)

In [32]:
df['unit_cost'] = df['total_cost']
df['quantity'] = 1
df['sub_category'] = 'Registration'
df['category'] = 'Buying'

In [30]:
df = df.reindex(columns = ['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category'])

In [45]:
df.loc[0, 'sub_category'] = 'Cost'

In [21]:
df['item'] = np.where(df['item'] == 'Physical Plan 1', 'Physical Plan Guy 1', df['item'])

In [24]:
df['item'] = np.where(df['item'] == 'Physical Plan 2', 'Physical Plan Guy 2', df['item'])

In [41]:
df['exchange_rate'] = 49.00

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           12 non-null     str
 1   quantity       12 non-null     int64
 2   unit_cost      12 non-null     int64
 3   total_cost     12 non-null     int64
 4   date           12 non-null     datetime64[us]
 5   sub_category   12 non-null     str
 6   category       12 non-null     str
 7   exchange_rate  12 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 900.0 bytes

In [37]:
df['date'] = pd.to_datetime(df['date'])

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item           12 non-null     str
 1   quantity       12 non-null     int64
 2   unit_cost      12 non-null     int64
 3   total_cost     12 non-null     int64
 4   date           12 non-null     datetime64[us]
 5   sub_category   12 non-null     str
 6   category       12 non-null     str
 7   exchange_rate  12 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 900.0 bytes

In [48]:
df

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Paradise View Plot: 20m x 25m,1,750000,750000,2019-08-03,Cost,Buying,49.0
1,Physical Plan Guy 1,1,1500,1500,2019-08-09,Registration,Buying,49.0
2,Physical Plan Guy 2,1,1000,1000,2019-12-17,Registration,Buying,49.0
3,MoneyTra Fee,1,490,490,2020-02-06,Registration,Buying,49.0
4,Physical Plan Guy 2,1,2000,2000,2020-02-07,Registration,Buying,49.0
5,GTBank Fee,1,5000,5000,2020-02-07,Registration,Buying,49.0
6,Gas for Car,1,500,500,2020-02-07,Registration,Buying,49.0
7,Chief Area Council,1,2000,2000,2020-02-10,Registration,Buying,49.0
8,Gas for Car,1,500,500,2020-02-10,Registration,Buying,49.0
9,Lady Filled Forms,1,400,400,2020-02-10,Registration,Buying,49.0
10,Sukuta Alkalo,1,1500,1500,2020-02-11,Registration,Buying,49.0
11,Gas,1,100,100,2020-02-11,Registration,Buying,49.0

In [49]:
df.to_csv('ParadiseView/out/df_cost.csv', index=False)