In [37]:
import pandas as pd
import numpy as np

In [38]:
cost = pd.read_csv('ParadiseView/out/df_cost.csv')

In [39]:
fencing = pd.read_csv('ParadiseView/out/df_fencing.csv')

In [40]:
borehole = pd.read_csv('ParadiseView/out/df_borehole_drill.csv')

In [41]:
cont_consul = pd.read_csv('ParadiseView/out/df_contractor_consul.csv')

In [42]:
otherExp = pd.read_csv('ParadiseView/out/df_otherExp_clean.csv')

In [43]:
cost

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Paradise View Plot: 20m x 25m,1,750000,750000,2019-08-03,Cost,Buying,49.0
1,Physical Plan Guy 1,1,1500,1500,2019-08-09,Registration,Buying,49.0
2,Physical Plan Guy 2,1,1000,1000,2019-12-17,Registration,Buying,49.0
3,MoneyTra Fee,1,490,490,2020-02-06,Registration,Buying,49.0
4,Physical Plan Guy 2,1,2000,2000,2020-02-07,Registration,Buying,49.0
5,GTBank Fee,1,5000,5000,2020-02-07,Registration,Buying,49.0
6,Gas for Car,1,500,500,2020-02-07,Registration,Buying,49.0
7,Chief Area Council,1,2000,2000,2020-02-10,Registration,Buying,49.0
8,Gas for Car,1,500,500,2020-02-10,Registration,Buying,49.0
9,Lady Filled Forms,1,400,400,2020-02-10,Registration,Buying,49.0
10,Sukuta Alkalo,1,1500,1500,2020-02-11,Registration,Buying,49.0
11,Gas,1,100,100,2020-02-11,Registration,Buying,49.0

In [44]:
fencing

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cutting Trees,1,10000,10000,2020-04-30,Fencing,Preconstruction,49.0
1,Big Trip of Sand,1,7500,7500,2020-04-30,Fencing,Preconstruction,49.0
2,Small Trip of Sand,1,4000,4000,2020-04-30,Fencing,Preconstruction,49.0
3,Cement,40,285,11400,2020-05-06,Fencing,Preconstruction,49.0
4,Cement Transport,1,600,600,2020-05-06,Fencing,Preconstruction,49.0
5,Wheelbarrow Rental,1,200,200,2020-05-06,Fencing,Preconstruction,49.0
6,Molding Bricks,1370,5,6850,2020-05-06,Fencing,Preconstruction,49.0
7,Water for Molding,1,1000,1000,2020-05-06,Fencing,Preconstruction,49.0
8,Gas for Transport,1,450,450,2020-05-06,Fencing,Preconstruction,49.0
9,Police Ticket,1,200,200,2020-04-29,Fencing,Preconstruction,49.0
10,Trip of Pebbles,1,3500,3500,2020-05-08,Fencing,Preconstruction,49.0
11,Cement,25,285,7125,2020-05-08,Fencing,Preconstruction,49.0
12,Cement Transport,25,15,375,2020-05-08,Fencing,Preconstruction,49.0
13,Papa Jara Transport,1,600,600,2020-05-08,Fencing,Preconstruction,49.0
14,Gas for Transport,1,200,200,2020-05-08,Fencing,Preconstruction,49.0
15,Iron Rods,1,4550,4550,2020-05-10,Fencing,Preconstruction,49.0
16,Iron Rods Transport,1,200,200,2020-05-10,Fencing,Preconstruction,49.0
17,Gas for Transport,1,125,125,2020-05-10,Fencing,Preconstruction,49.0
18,Gas for Transport,1,400,400,2020-05-16,Fencing,Preconstruction,49.0
19,Electric Pipes,4,35,140,2020-05-16,Fencing,Preconstruction,49.0
20,Wire for Pillar Board,1,100,100,2020-05-16,Fencing,Preconstruction,49.0
21,Kilo of Nales,2,60,120,2020-05-16,Fencing,Preconstruction,49.0
22,Taxi Fare,1,250,250,2020-05-16,Fencing,Preconstruction,49.0
23,Pillar Boardrent 2Ds,14,50,700,2020-05-16,Fencing,Preconstruction,49.0
24,Pillar Iron Rods,4,600,2400,2020-05-16,Fencing,Preconstruction,49.0
25,Cement,4,285,1150,2020-05-22,Fencing,Preconstruction,49.0
26,Gas for Transport,1,200,200,2020-05-22,Fencing,Preconstruction,49.0
27,Pillar Mold Rental,4,500,2000,2020-05-22,Fencing,Preconstruction,49.0
28,Pillar Board Rental,6,25,150,2020-02-22,Fencing,Preconstruction,49.0
29,Pillar & Board Trasp,1,1000,1000,2020-05-22,Fencing,Preconstruction,49.0
30,Pillar Pebbel,1,3000,3000,2020-05-22,Fencing,Preconstruction,49.0
31,Pillar Pebbel Trasport,1,400,400,2020-05-22,Fencing,Preconstruction,49.0
32,Lock for Gate,1,250,250,2020-05-22,Fencing,Preconstruction,49.0
33,Gate,1,26000,26000,2020-05-22,Fencing,Preconstruction,49.0
34,Cement,5,285,1425,2020-05-22,Fencing,Preconstruction,49.0
35,Cement Transport,5,15,75,2020-05-22,Fencing,Preconstruction,49.0
36,Fence Building Fee,1,12000,12000,2020-05-24,Fencing,Preconstruction,49.0
37,Water for Fencing,1,1000,1000,2020-05-24,Fencing,Preconstruction,49.0
38,Finishing,1,1000,1000,2020-06-23,Fencing,Preconstruction,49.0

In [45]:
borehole

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Bore Drilling,1.0,95000.0,95000.0,2023-06-24,Borehole Drilling,Preconstruction,63.0
1,Carpenter,1.0,6500.0,6500.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
2,Kaye Rod,34.0,180.0,6120.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
3,Polycarbonate Roof Panel(Packs),2.5,4300.0,10750.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
4,Big Nale(kg),3.0,100.0,300.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
5,Small Nale(Packs),3.0,350.0,1050.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
6,Wood for Doors,5.0,300.0,1500.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
7,Cutting Mango Branch and Moving Bricks,1.0,1600.0,1600.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
8,Delivering Guys,1.0,800.0,800.0,2023-06-25,Borehole Drilling,Preconstruction,63.0
9,Residual,1.0,2380.0,2380.0,2023-06-25,Borehole Drilling,Preconstruction,63.0

In [46]:
cont_consul

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Consulting Contractors,1,4000,4000,2023-09-25,Contractor Consultation,Preconstruction,61.5
1,Clearing the Area,1,8000,8000,2023-12-21,Contractor Consultation,Preconstruction,64.0
2,Transportation,1,2000,2000,2023-12-21,Contractor Consultation,Preconstruction,64.0
3,Bubacarr Fai,1,2000,2000,2023-12-20,Contractor Consultation,Preconstruction,64.0

In [47]:
otherExp

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Papa Jara,1,2000.0,2000.0,2020-03-23,Fencing,Preconstruction,49.0
1,Bubacarr Faye,1,1500.0,1500.0,2020-04-29,Fencing,Preconstruction,49.0
2,Papa Jara,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
3,Bubacarr Faye,1,2000.0,2000.0,2020-05-23,Fencing,Preconstruction,49.0
4,Papa Jara,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0
5,Bubacarr Faye,1,2500.0,2500.0,2020-04-23,Fencing,Preconstruction,49.0

In [48]:
cost_to_precons = pd.concat([cost, otherExp, fencing, borehole, cont_consul], axis=0, ignore_index=True)

In [49]:
print(cost_to_precons.to_string())

                                      item  quantity  unit_cost  total_cost        date             sub_category         category  exchange_rate
0            Paradise View Plot: 20m x 25m       1.0   750000.0    750000.0  2019-08-03                     Cost           Buying           49.0
1                      Physical Plan Guy 1       1.0     1500.0      1500.0  2019-08-09             Registration           Buying           49.0
2                      Physical Plan Guy 2       1.0     1000.0      1000.0  2019-12-17             Registration           Buying           49.0
3                             MoneyTra Fee       1.0      490.0       490.0  2020-02-06             Registration           Buying           49.0
4                      Physical Plan Guy 2       1.0     2000.0      2000.0  2020-02-07             Registration           Buying           49.0
5                               GTBank Fee       1.0     5000.0      5000.0  2020-02-07             Registration           Buying           49.0
6                              Gas for Car       1.0      500.0       500.0  2020-02-07             Registration           Buying           49.0
7                      Chief Area Council        1.0     2000.0      2000.0  2020-02-10             Registration           Buying           49.0
8                              Gas for Car       1.0      500.0       500.0  2020-02-10             Registration           Buying           49.0
9                        Lady Filled Forms       1.0      400.0       400.0  2020-02-10             Registration           Buying           49.0
10                           Sukuta Alkalo       1.0     1500.0      1500.0  2020-02-11             Registration           Buying           49.0
11                                     Gas       1.0      100.0       100.0  2020-02-11             Registration           Buying           49.0
12                               Papa Jara       1.0     2000.0      2000.0  2020-03-23                  Fencing  Preconstruction           49.0
13                           Bubacarr Faye       1.0     1500.0      1500.0  2020-04-29                  Fencing  Preconstruction           49.0
14                               Papa Jara       1.0     2000.0      2000.0  2020-05-23                  Fencing  Preconstruction           49.0
15                           Bubacarr Faye       1.0     2000.0      2000.0  2020-05-23                  Fencing  Preconstruction           49.0
16                               Papa Jara       1.0     2500.0      2500.0  2020-04-23                  Fencing  Preconstruction           49.0
17                           Bubacarr Faye       1.0     2500.0      2500.0  2020-04-23                  Fencing  Preconstruction           49.0
18                           Cutting Trees       1.0    10000.0     10000.0  2020-04-30                  Fencing  Preconstruction           49.0
19                        Big Trip of Sand       1.0     7500.0      7500.0  2020-04-30                  Fencing  Preconstruction           49.0
20                      Small Trip of Sand       1.0     4000.0      4000.0  2020-04-30                  Fencing  Preconstruction           49.0
21                                 Cement       40.0      285.0     11400.0  2020-05-06                  Fencing  Preconstruction           49.0
22                       Cement Transport        1.0      600.0       600.0  2020-05-06                  Fencing  Preconstruction           49.0
23                      Wheelbarrow Rental       1.0      200.0       200.0  2020-05-06                  Fencing  Preconstruction           49.0
24                          Molding Bricks    1370.0        5.0      6850.0  2020-05-06                  Fencing  Preconstruction           49.0
25                      Water for Molding        1.0     1000.0      1000.0  2020-05-06                  Fencing  Preconstruction           49.0
26                      Gas for Transport        1.0      450.0       450.0  2020-05-06                  Fencing  Preconstruction           49.0
27                          Police Ticket        1.0      200.0       200.0  2020-04-29                  Fencing  Preconstruction           49.0
28                        Trip of Pebbles        1.0     3500.0      3500.0  2020-05-08                  Fencing  Preconstruction           49.0
29                                 Cement       25.0      285.0      7125.0  2020-05-08                  Fencing  Preconstruction           49.0
30                       Cement Transport       25.0       15.0       375.0  2020-05-08                  Fencing  Preconstruction           49.0
31                     Papa Jara Transport       1.0      600.0       600.0  2020-05-08                  Fencing  Preconstruction           49.0
32                      Gas for Transport        1.0      200.0       200.0  2020-05-08                  Fencing  Preconstruction           49.0
33                               Iron Rods       1.0     4550.0      4550.0  2020-05-10                  Fencing  Preconstruction           49.0
34                    Iron Rods Transport        1.0      200.0       200.0  2020-05-10                  Fencing  Preconstruction           49.0
35                      Gas for Transport        1.0      125.0       125.0  2020-05-10                  Fencing  Preconstruction           49.0
36                      Gas for Transport        1.0      400.0       400.0  2020-05-16                  Fencing  Preconstruction           49.0
37                         Electric Pipes        4.0       35.0       140.0  2020-05-16                  Fencing  Preconstruction           49.0
38                   Wire for Pillar Board       1.0      100.0       100.0  2020-05-16                  Fencing  Preconstruction           49.0
39                           Kilo of Nales       2.0       60.0       120.0  2020-05-16                  Fencing  Preconstruction           49.0
40                              Taxi Fare        1.0      250.0       250.0  2020-05-16                  Fencing  Preconstruction           49.0
41                    Pillar Boardrent 2Ds      14.0       50.0       700.0  2020-05-16                  Fencing  Preconstruction           49.0
42                        Pillar Iron Rods       4.0      600.0      2400.0  2020-05-16                  Fencing  Preconstruction           49.0
43                                 Cement        4.0      285.0      1150.0  2020-05-22                  Fencing  Preconstruction           49.0
44                      Gas for Transport        1.0      200.0       200.0  2020-05-22                  Fencing  Preconstruction           49.0
45                     Pillar Mold Rental        4.0      500.0      2000.0  2020-05-22                  Fencing  Preconstruction           49.0
46                    Pillar Board Rental        6.0       25.0       150.0  2020-02-22                  Fencing  Preconstruction           49.0
47                    Pillar & Board Trasp       1.0     1000.0      1000.0  2020-05-22                  Fencing  Preconstruction           49.0
48                           Pillar Pebbel       1.0     3000.0      3000.0  2020-05-22                  Fencing  Preconstruction           49.0
49                  Pillar Pebbel Trasport       1.0      400.0       400.0  2020-05-22                  Fencing  Preconstruction           49.0
50                           Lock for Gate       1.0      250.0       250.0  2020-05-22                  Fencing  Preconstruction           49.0
51                                    Gate       1.0    26000.0     26000.0  2020-05-22                  Fencing  Preconstruction           49.0
52                                 Cement        5.0      285.0      1425.0  2020-05-22                  Fencing  Preconstruction           49.0
53                       Cement Transport        5.0       15.0        75.0  2020-05-22                  Fencing  Preconstruction           49.0
54                      Fence Building Fee       1.0    12000.0     12000.0  2020-05-24                  Fencing  Preconstruction           49.0
55                      Water for Fencing        1.0     1000.0      1000.0  2020-05-24                  Fencing  Preconstruction           49.0
56                              Finishing        1.0     1000.0      1000.0  2020-06-23                  Fencing  Preconstruction           49.0
57                           Bore Drilling       1.0    95000.0     95000.0  2023-06-24        Borehole Drilling  Preconstruction           63.0
58                               Carpenter       1.0     6500.0      6500.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
59                                Kaye Rod      34.0      180.0      6120.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
60         Polycarbonate Roof Panel(Packs)       2.5     4300.0     10750.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
61                            Big Nale(kg)       3.0      100.0       300.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
62                       Small Nale(Packs)       3.0      350.0      1050.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
63                          Wood for Doors       5.0      300.0      1500.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
64  Cutting Mango Branch and Moving Bricks       1.0     1600.0      1600.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
65                         Delivering Guys       1.0      800.0       800.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
66                                Residual       1.0     2380.0      2380.0  2023-06-25        Borehole Drilling  Preconstruction           63.0
67                  Consulting Contractors       1.0     4000.0      4000.0  2023-09-25  Contractor Consultation  Preconstruction           61.5
68                       Clearing the Area       1.0     8000.0      8000.0  2023-12-21  Contractor Consultation  Preconstruction           64.0
69                         Transportation        1.0     2000.0      2000.0  2023-12-21  Contractor Consultation  Preconstruction           64.0
70                            Bubacarr Fai       1.0     2000.0      2000.0  2023-12-20  Contractor Consultation  Preconstruction           64.0

In [50]:
cost_to_precons.to_csv('ParadiseView/clean/cost_to_preconstruction.csv', index=False)