In [10]:
import pandas as pd
import numpy as np

In [11]:
bricks = pd.read_csv('ParadiseView/out/df_ffBrickMolding.csv')

In [12]:
const = pd.read_csv('ParadiseView/out/firstFloor_const.csv')

In [13]:
bricks

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,$100 Transfer Fee,1.0,250.0,250.0,2022-03-27,Brick Molding,1st Floor,50.0
1,Cutting Trees,1.0,5000.0,5000.0,2022-04-03,Brick Molding,1st Floor,50.0
2,Clearing Plot,1.0,2500.0,2500.0,2022-04-03,Brick Molding,1st Floor,50.0
3,"$1,000 Transfer Fee",1.0,1000.0,1000.0,2022-04-16,Brick Molding,1st Floor,50.0
4,Cement,75.0,320.0,24000.0,2022-04-18,Brick Molding,1st Floor,50.0
5,Cement Transport,75.0,20.0,1500.0,2022-04-18,Brick Molding,1st Floor,50.0
6,Wheelbarrow,1.0,3000.0,3000.0,2022-04-18,Brick Molding,1st Floor,50.0
7,50m Hose/Pipe,1.0,1400.0,1400.0,2022-04-18,Brick Molding,1st Floor,50.0
8,Small Bucket,2.0,100.0,200.0,2022-04-18,Brick Molding,1st Floor,50.0
9,Big Sand Trip,2.0,8000.0,16000.0,2022-04-18,Brick Molding,1st Floor,50.0
10,Small Tank,1.0,1600.0,1600.0,2022-04-18,Brick Molding,1st Floor,50.0
11,Cement Watchman,1.0,500.0,500.0,2022-04-18,Brick Molding,1st Floor,50.0
12,Gasoline,1.0,300.0,300.0,2022-04-18,Brick Molding,1st Floor,50.0
13,Missing,1.0,1500.0,1500.0,2022-04-18,Brick Molding,1st Floor,50.0
14,"$1,000 Transfer Fee",1.0,1000.0,1000.0,2022-04-19,Brick Molding,1st Floor,50.0
15,Cement,120.0,325.0,39000.0,2022-04-20,Brick Molding,1st Floor,50.0
16,Cement Transport,120.0,15.0,1800.0,2022-04-20,Brick Molding,1st Floor,50.0
17,Big Sand Trip,1.0,8000.0,8000.0,2022-04-20,Brick Molding,1st Floor,50.0
18,Small Tank,1.0,800.0,800.0,2022-04-20,Brick Molding,1st Floor,50.0
19,Wheelbarrow Tire,1.0,700.0,700.0,2022-04-20,Brick Molding,1st Floor,50.0
20,Gasoline,1.0,500.0,500.0,2022-04-20,Brick Molding,1st Floor,50.0
21,"$1,000 Transfer Fee",1.0,600.0,600.0,2022-04-22,Brick Molding,1st Floor,50.0
22,Big Sand Trip,2.0,8000.0,16000.0,2022-04-23,Brick Molding,1st Floor,50.0
23,Bricks Payment,4210.0,6.0,25260.0,2022-04-23,Brick Molding,1st Floor,50.0
24,Over Payment,1.0,1800.0,1800.0,2022-04-23,Brick Molding,1st Floor,50.0
25,Big Sand Trip,1.0,8000.0,8000.0,2022-04-23,Brick Molding,1st Floor,50.0
26,6Wheel Sand Trip,1.0,5500.0,5500.0,2022-04-23,Brick Molding,1st Floor,50.0
27,Cement,55.0,330.0,18150.0,2022-04-23,Brick Molding,1st Floor,50.0
28,Cement Transport,55.0,15.0,825.0,2022-04-23,Brick Molding,1st Floor,50.0
29,Bricks payment,2675.0,6.0,16050.0,2022-04-23,Brick Molding,1st Floor,50.0
30,Needs To Be Determined,1.0,15.0,15.0,2022-04-23,Brick Molding,1st Floor,50.0

In [14]:
const

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,1 by 2 wood,25,100.0,2500.0,2024-01-01,Construction,1st Floor,67.50
1,Wooden Pake,15,35.0,500.0,2024-01-01,Construction,1st Floor,67.50
2,3 Inches Nale(kg),2,100.0,200.0,2024-01-01,Construction,1st Floor,67.50
3,2 and half Inches Nale(kg),2,100.0,200.0,2024-01-01,Construction,1st Floor,67.50
4,Materials Transportation,1,500.0,500.0,2024-01-01,Construction,1st Floor,67.50
...,...,...,...,...,...,...,...,...
337,Returning Roof Concrete Materials,1,8500.0,8500.0,2025-05-17,Roof Concreting,1st Floor,72.25
338,Cement Transport,25,20.0,500.0,2025-04-24,Roof Concreting,1st Floor,72.85
339,Cemennt,38,415.0,15770.0,2024-06-11,Brick Molding,1st Floor,71.20
340,Cemennt Transport,38,30.0,1140.0,2024-06-11,Brick Molding,1st Floor,71.20
341,Cemennt Transport,38,30.0,1140.0,2024-06-11,Brick Molding,1st Floor,71.20

In [15]:
floorOne = pd.concat([bricks, const], axis=0, ignore_index=True)

In [16]:
print(floorOne.to_string())

                                    item  quantity  unit_cost  total_cost        date     sub_category   category  exchange_rate
0                      $100 Transfer Fee       1.0      250.0       250.0  2022-03-27    Brick Molding  1st Floor          50.00
1                          Cutting Trees       1.0     5000.0      5000.0  2022-04-03    Brick Molding  1st Floor          50.00
2                          Clearing Plot       1.0     2500.0      2500.0  2022-04-03    Brick Molding  1st Floor          50.00
3                    $1,000 Transfer Fee       1.0     1000.0      1000.0  2022-04-16    Brick Molding  1st Floor          50.00
4                                Cement       75.0      320.0     24000.0  2022-04-18    Brick Molding  1st Floor          50.00
5                       Cement Transport      75.0       20.0      1500.0  2022-04-18    Brick Molding  1st Floor          50.00
6                           Wheelbarrow        1.0     3000.0      3000.0  2022-04-18    Brick Molding  1st Floor          50.00
7                         50m Hose/Pipe        1.0     1400.0      1400.0  2022-04-18    Brick Molding  1st Floor          50.00
8                          Small Bucket        2.0      100.0       200.0  2022-04-18    Brick Molding  1st Floor          50.00
9                          Big Sand Trip       2.0     8000.0     16000.0  2022-04-18    Brick Molding  1st Floor          50.00
10                           Small Tank        1.0     1600.0      1600.0  2022-04-18    Brick Molding  1st Floor          50.00
11                       Cement Watchman       1.0      500.0       500.0  2022-04-18    Brick Molding  1st Floor          50.00
12                             Gasoline        1.0      300.0       300.0  2022-04-18    Brick Molding  1st Floor          50.00
13                              Missing        1.0     1500.0      1500.0  2022-04-18    Brick Molding  1st Floor          50.00
14                   $1,000 Transfer Fee       1.0     1000.0      1000.0  2022-04-19    Brick Molding  1st Floor          50.00
15                               Cement      120.0      325.0     39000.0  2022-04-20    Brick Molding  1st Floor          50.00
16                      Cement Transport     120.0       15.0      1800.0  2022-04-20    Brick Molding  1st Floor          50.00
17                         Big Sand Trip       1.0     8000.0      8000.0  2022-04-20    Brick Molding  1st Floor          50.00
18                           Small Tank        1.0      800.0       800.0  2022-04-20    Brick Molding  1st Floor          50.00
19                     Wheelbarrow Tire        1.0      700.0       700.0  2022-04-20    Brick Molding  1st Floor          50.00
20                             Gasoline        1.0      500.0       500.0  2022-04-20    Brick Molding  1st Floor          50.00
21                   $1,000 Transfer Fee       1.0      600.0       600.0  2022-04-22    Brick Molding  1st Floor          50.00
22                        Big Sand Trip        2.0     8000.0     16000.0  2022-04-23    Brick Molding  1st Floor          50.00
23                       Bricks Payment     4210.0        6.0     25260.0  2022-04-23    Brick Molding  1st Floor          50.00
24                         Over Payment        1.0     1800.0      1800.0  2022-04-23    Brick Molding  1st Floor          50.00
25                         Big Sand Trip       1.0     8000.0      8000.0  2022-04-23    Brick Molding  1st Floor          50.00
26                      6Wheel Sand Trip       1.0     5500.0      5500.0  2022-04-23    Brick Molding  1st Floor          50.00
27                               Cement       55.0      330.0     18150.0  2022-04-23    Brick Molding  1st Floor          50.00
28                     Cement Transport       55.0       15.0       825.0  2022-04-23    Brick Molding  1st Floor          50.00
29                       Bricks payment     2675.0        6.0     16050.0  2022-04-23    Brick Molding  1st Floor          50.00
30                Needs To Be Determined       1.0       15.0        15.0  2022-04-23    Brick Molding  1st Floor          50.00
31                           1 by 2 wood      25.0      100.0      2500.0  2024-01-01     Construction  1st Floor          67.50
32                           Wooden Pake      15.0       35.0       500.0  2024-01-01     Construction  1st Floor          67.50
33                    3 Inches Nale(kg)        2.0      100.0       200.0  2024-01-01     Construction  1st Floor          67.50
34           2 and half Inches Nale(kg)        2.0      100.0       200.0  2024-01-01     Construction  1st Floor          67.50
35             Materials Transportation        1.0      500.0       500.0  2024-01-01     Construction  1st Floor          67.50
36            Floor Plan Copy/Laminating       1.0      550.0       550.0  2024-01-02     Construction  1st Floor          67.50
37                   50m Water Hose/Pipe       1.0     1500.0      1500.0  2024-01-06     Construction  1st Floor          67.50
38                        Iron Rod(12mm)     100.0      540.0     54000.0  2024-01-11     Construction  1st Floor          67.50
39                         Iron Rod(6mm)     100.0      150.0     15000.0  2024-01-11     Construction  1st Floor          67.50
40                                Cement     100.0      405.0     40500.0  2024-01-11     Construction  1st Floor          67.50
41                          Wheelbarrow        1.0     2700.0      2700.0  2024-01-11     Construction  1st Floor          67.50
42                  Binding Wire(Bundle)       2.0      425.0       850.0  2024-01-11     Construction  1st Floor          67.50
43             Materials Transportation        1.0     3800.0      3800.0  2024-01-11     Construction  1st Floor          67.50
44                       Sand (10 Wheel)       1.0     7500.0      7500.0  2024-01-11     Construction  1st Floor          67.50
45              Clean Pebble(10 Wheels)        1.0    12000.0     12000.0  2024-01-11     Construction  1st Floor          67.50
46           Sulaiman Juwara(Contractor)       1.0   100000.0    100000.0  2024-01-11     Construction  1st Floor          67.50
47                  Bubacar Fai Payment        1.0    12000.0     12000.0  2024-01-11     Construction  1st Floor          67.50
48           Asphalt Stones(double trip)       1.0    84000.0     84000.0  2024-01-27     Construction  1st Floor          71.20
49              Cement For Guard's Room        7.0      400.0      2800.0  2024-01-29     Construction  1st Floor          71.20
50                    Transport(Cements)       1.0      150.0       150.0  2024-01-29     Construction  1st Floor          71.20
51             Guard's Room Fl Concrete        1.0     3000.0      3000.0  2024-01-29     Construction  1st Floor          71.20
52                             Mattress        1.0     2300.0      2300.0  2024-02-05     Construction  1st Floor          71.20
53                   Mattress Transport        1.0      300.0       300.0  2024-02-05     Construction  1st Floor          71.20
54                        Machete Knife        1.0      200.0       200.0  2024-02-05     Construction  1st Floor          71.20
55                                  Lock       2.0      125.0       250.0  2024-02-05     Construction  1st Floor          71.20
56                 Kettle and Prayer Mat       1.0      275.0       275.0  2024-02-05     Construction  1st Floor          71.20
57                    Chain For Door(1m)       1.0      300.0       300.0  2024-02-05     Construction  1st Floor          71.20
58                       Slide Bolt Lock       1.0       60.0        60.0  2024-02-05     Construction  1st Floor          71.20
59              Flashlight with Battery        1.0       90.0        90.0  2024-02-05     Construction  1st Floor          71.20
60                  Carpenter for Locks        1.0      200.0       200.0  2024-02-05     Construction  1st Floor          71.20
61              Borehole Reinstallation        1.0      800.0       800.0  2024-02-13     Construction  1st Floor          71.20
62                 Guard Room Door locks       1.0      125.0       125.0  2024-02-13     Construction  1st Floor          71.20
63                            Carpenter        1.0      200.0       200.0  2024-02-13     Construction  1st Floor          71.20
64                              Tap Head       1.0      350.0       350.0  2024-02-13     Construction  1st Floor          71.20
65                   Generator Transport       1.0      600.0       600.0  2024-02-14     Construction  1st Floor          71.20
66                          1 by 12 Wood       8.0      650.0      5200.0  2024-02-20     Construction  1st Floor          71.20
67               1 by 12 Wood Transport        1.0      700.0       700.0  2024-02-20     Construction  1st Floor          71.20
68                            Generator        1.0    11000.0     11000.0  2024-02-20     Construction  1st Floor          71.20
69                  Generator Transport        1.0      600.0       600.0  2024-02-20     Construction  1st Floor          71.20
70                Gas for the Generator        1.0      400.0       400.0  2024-02-20     Construction  1st Floor          71.20
71                           Momo Waggeh       1.0      500.0       500.0  2024-02-20     Construction  1st Floor          71.20
72            Rice(50kg) for Momo Waggeh       1.0     2000.0      2000.0  2024-02-24     Construction  1st Floor          71.20
73                       Sand (10 Wheel)       1.0     7500.0      7500.0  2024-03-01     Construction  1st Floor          71.20
74                               Cement      100.0      395.0     39500.0  2024-03-05     Construction  1st Floor          71.20
75                     Cement Transport        1.0     2000.0      2000.0  2024-03-05     Construction  1st Floor          71.20
76                           1 by 2 Wood      60.0      100.0      6000.0  2024-03-05     Construction  1st Floor          71.20
77                        Plywood(12mm)       10.0     1550.0     15500.0  2024-03-05     Construction  1st Floor          71.20
78               Splitting 12mm plywood       10.0       75.0       750.0  2024-03-05     Construction  1st Floor          71.20
79               12mm plywood Transport        1.0      700.0       700.0  2024-03-05     Construction  1st Floor          71.20
80           Momo Waggeh Salary (March)        1.0     4000.0      4000.0  2024-03-05     Construction  1st Floor          71.20
81                              Nail(kg)       9.0      100.0       900.0  2024-03-05     Construction  1st Floor          71.20
82                  Binding Wire(Bundle)       2.0      475.0       950.0  2024-03-12     Construction  1st Floor          71.20
83                      PS 10mm Iron Rod     100.0      340.0     34000.0  2024-03-12     Construction  1st Floor          71.20
84            Binding Wire+IronRod Trans       1.0      800.0       800.0  2024-03-12     Construction  1st Floor          71.20
85                  Workers Ramadan Gift       1.0      400.0       400.0  2024-03-12     Construction  1st Floor          71.20
86                         Iron Rod(6mm)      25.0      150.0      3750.0  2024-03-13     Construction  1st Floor          71.20
87                        6mm Transport        1.0      400.0       400.0  2024-03-13     Construction  1st Floor          71.20
88                          Gas + Nails        1.0      500.0       500.0  2024-03-13     Construction  1st Floor          71.20
89                       Sand (10 Wheel)       1.0     7500.0      7500.0  2024-03-23     Construction  1st Floor          71.20
90                           BCF Ramadan       1.0     2000.0      2000.0  2024-03-24     Construction  1st Floor          71.20
91                                Cement      50.0      390.0     19500.0  2024-03-25     Construction  1st Floor          71.20
92                     Cement Transport       50.0       20.0      1000.0  2024-03-25     Construction  1st Floor          71.20
93                Gas for the Generator        1.0      300.0       300.0  2024-03-27     Construction  1st Floor          71.20
94                        Iron Rod(12mm)      90.0      510.0     45900.0  2024-03-29     Construction  1st Floor          71.20
95                        Iron Rod(10mm)     100.0      325.0     32500.0  2024-03-29     Construction  1st Floor          71.20
96                       PS 6mm Iron Rod      85.0      135.0     11400.0  2024-03-29     Construction  1st Floor          71.20
97                  Binding Wire(Bundle)       3.0      400.0      1200.0  2024-03-29     Construction  1st Floor          71.20
98         Iron Rod + Binding Wire Trans       1.0     2000.0      2000.0  2024-03-29     Construction  1st Floor          71.20
99                      Timber for Sappo      20.0      200.0      4000.0  2024-03-29     Construction  1st Floor          71.20
100                    Timber Transport        1.0      650.0       650.0  2024-03-29     Construction  1st Floor          71.20
101                      Sand (10 Wheel)       1.0     7500.0      7500.0  2024-03-29     Construction  1st Floor          71.20
102           Momo Waggeh Salary (April)       1.0     4000.0      4000.0  2024-04-04     Construction  1st Floor          71.20
103                          Nail(kg) 3"       5.0      100.0       500.0  2024-04-04     Construction  1st Floor          71.20
104                      Nail(kg) 2 1/2"       5.0      100.0       500.0  2024-04-04     Construction  1st Floor          71.20
105                        Timber 1 by 6      10.0      300.0      3000.0  2024-04-07     Construction  1st Floor          71.20
106             Timber 1 by 6 Transport        1.0      500.0       500.0  2024-04-07     Construction  1st Floor          71.20
107             Wheelbarrow Maintenance        2.0     1000.0      2000.0  2024-04-08     Construction  1st Floor          71.20
108         Momo Waggeh Salary(advanced)       1.0     4000.0      4000.0  2024-04-19     Construction  1st Floor          71.20
109       Moving Sand from the Yard(1st)       1.0      350.0       350.0  2024-04-23     Construction  1st Floor          71.20
110       Moving Sand from the Yard(2nd)       2.0      350.0       700.0  2024-04-23     Construction  1st Floor          71.20
111       Moving Sand from the Yard(3rd)       4.0      400.0      1600.0  2024-04-23     Construction  1st Floor          71.20
112       Moving Sand from the Yard(4th)       3.0      500.0      1500.0  2024-04-23     Construction  1st Floor          71.20
113                               Cement      50.0      390.0     19500.0  2024-04-23    Brick Molding  1st Floor          71.20
114                    Cement Transport       50.0       20.0      1000.0  2024-04-23    Brick Molding  1st Floor          71.20
115                            Tape Head       1.0      350.0       350.0  2024-04-23     Construction  1st Floor          71.20
116                           Tape Cover       1.0      150.0       150.0  2024-04-23     Construction  1st Floor          71.20
117                  Lock for Tape Cover       1.0      100.0       100.0  2024-04-23     Construction  1st Floor          71.20
118                      Sand (10 Wheel)       1.0     7500.0      7500.0  2024-04-26    Brick Molding  1st Floor          71.20
119               Gas for the Generator        1.0      375.0       375.0  2024-04-29     Construction  1st Floor          71.20
120    Generator Leaking Repair + Trans        1.0      700.0       700.0  2024-04-29     Construction  1st Floor          71.20
121                               Cement      50.0      395.0     19750.0  2024-05-01    Brick Molding  1st Floor          71.20
122                    Cement Transport       50.0       20.0      1000.0  2024-05-01    Brick Molding  1st Floor          71.20
123                      Sand (10 Wheel)       1.0     7500.0      7500.0  2024-05-02    Brick Molding  1st Floor          71.20
124                               Cement      50.0      380.0     19000.0  2024-05-04    Brick Molding  1st Floor          71.20
125                    Cement Transport       50.0       20.0      1000.0  2024-05-04    Brick Molding  1st Floor          71.20
126               Generator Repair + Gas       1.0     1200.0      1200.0  2024-05-04     Construction  1st Floor          71.20
127                   Oil for Generator        1.0      150.0       150.0  2024-05-06     Construction  1st Floor          71.20
128                      Sand (10 Wheel)       1.0     7500.0      7500.0  2024-05-07    Brick Molding  1st Floor          71.20
129               Gas for the Generator        1.0      350.0       350.0  2024-05-07     Construction  1st Floor          71.20
130                 Watering the Bricks        1.0      500.0       500.0  2024-05-10     Construction  1st Floor          71.20
131                      Bricks Molding     3708.0        6.0     22250.0  2024-05-18    Brick Molding  1st Floor          71.20
132               Gas for the Generator        1.0      400.0       400.0  2024-05-25     Construction  1st Floor          71.20
133                               Sadaqa       1.0     3000.0      3000.0  2024-05-26     Construction  1st Floor          71.20
134        Sulaiman Juwarra 2nd Payment        1.0    80000.0     80000.0  2024-05-27     Construction  1st Floor          71.20
135                       Iron Rod(12mm)     100.0      540.0     54000.0  2024-05-28     Construction  1st Floor          71.20
136                        Iron Rod(6mm)      25.0      150.0      3750.0  2024-05-28     Construction  1st Floor          71.20
137                               Cement      30.0      400.0     12000.0  2024-05-28     Construction  1st Floor          71.20
138             Cement + Rods Transport        1.0     1400.0      1400.0  2024-05-28     Construction  1st Floor          71.20
139             Clean Pebble(10 Wheels)        1.0    13500.0     13500.0  2024-05-28     Construction  1st Floor          71.20
140          Asphalt Stones(double trip)       1.0    95000.0     95000.0  2024-05-28     Construction  1st Floor          71.20
141                      Sand(10 Wheels)       1.0     7500.0      7500.0  2024-05-28     Construction  1st Floor          71.20
142         Bubacar Fai Advance Payment        6.0    12000.0     72000.0  2024-05-28     Construction  1st Floor          71.20
143                              Cement       50.0      400.0     20000.0  2024-05-30     Construction  1st Floor          71.20
144                    Cement Transport       50.0       30.0      1500.0  2024-05-30     Construction  1st Floor          71.20
145           Momo Waggeh Salary (June)        1.0     4000.0      4000.0  2024-06-03     Construction  1st Floor          71.20
146                               Cement     100.0      430.0     43000.0  2024-06-03     Construction  1st Floor          71.20
147                    Cement Transport      100.0       30.0      3000.0  2024-06-03     Construction  1st Floor          71.20
148                      Sand (10 Wheel)       1.0     7500.0      7500.0  2024-06-03     Construction  1st Floor          71.20
149               Gas for the Generator        1.0      950.0       950.0  2024-06-04     Construction  1st Floor          71.20
150                      Sand (10 Wheel)       1.0     7500.0      7500.0  2024-06-10     Construction  1st Floor          71.20
151                               Cement      62.0      415.0     25730.0  2024-06-11     Construction  1st Floor          71.20
152                    Cement Transport       62.0       30.0      1860.0  2024-06-11     Construction  1st Floor          71.20
153                             Nail(kg)       4.0      100.0       400.0  2024-06-14     Construction  1st Floor          71.20

In [18]:
floorOne.to_csv('ParadiseView/clean/floorOne.csv', index=False)