In [3]:
import pandas as pd
import numpy as np

In [4]:
thirdfloor_const = pd.read_csv('ParadiseView/Paradise View/3rdfloor_const.csv')

In [5]:
thirdfloor_const = thirdfloor_const.dropna(thresh=3)

In [6]:
thirdfloor_const.columns

Index(['ITEM', 'QUALITY ', 'UNIT PRICE(D)', 'COST(D)', 'DATE', 'COMMENT '], dtype='str')

In [7]:
thirdfloor_const.drop(columns='COMMENT ', inplace=True)

In [8]:
thirdfloor_const.columns = thirdfloor_const.columns.str.lower()

In [9]:
thirdfloor_const.columns

Index(['item', 'quality ', 'unit price(d)', 'cost(d)', 'date'], dtype='str')

In [12]:
thirdfloor_const.rename(columns={'quality ': 'quantity', 'unit price(d)': 'unit_cost', 'cost(d)': 'total_cost'}, inplace=True)

In [21]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Njaye Payment', 'Contractor Njaye Payment', thirdfloor_const['item'])

In [31]:
(thirdfloor_const['date'].isna())

66    False
67    False
68    False
69     True
70    False
Name: date, dtype: bool

In [39]:
thirdfloor_const['date'] = np.where(thirdfloor_const['date'].isna(), '04/20/2026', thirdfloor_const['date'])

In [35]:
print(thirdfloor_const.to_string())

                                  item  quantity   unit_cost  total_cost        date
0                               Cement      36.0      480.00   17,280.00  12/29/2026
1                    Cement Transport       36.0       20.00      720.00  12/29/2026
2                        Sand(10wheel)       1.0    8,000.00    8,000.00  12/29/2026
3             Contractor Njaye Payment       1.0  100,000.00  100,000.00  01/20/2026
4                       Iron Rod(12mm)     103.0      540.00   55,620.00  01/22/2026
5                         Binding Wire       1.0      500.00      500.00  01/22/2026
6   Iron Rod + Binding Wite Transport        1.0      700.00      700.00  01/22/2026
7                  Big Plastic Barrel        2.0    1,000.00    2,000.00  01/23/2026
8                   Barrels Transport        1.0      500.00      500.00  01/23/2026
9                   Gas for Generator        1.0      475.00      475.00  01/23/2026
10               Bubacarr Faye Payment       1.0   60,000.00   60,000.00  01/24/2026
11                              Cement     100.0      465.00   46,500.00  01/27/2026
12                   Cement Transport      100.0       20.00    2,000.00  01/27/2026
13                       Sand(10wheel)       1.0    8,000.00    8,000.00  01/27/2026
14            Contractor Njaye Payment       1.0  100,000.00  100,000.00  01/28/2026
15             Fixing Momo Haja’s Gate       1.0      700.00      700.00  01/29/2026
16                  Gas for Generator        1.0      500.00      500.00  01/30/2026
17                       Asphalt(95cu)       1.0   95,000.00   95,000.00  01/31/2026
18                            Nail(kg)      10.0      100.00    1,000.00  01/31/2026
19                       Ali’ Payment        1.0    5,500.00    5,500.00  02/04/2026
20            Generator Repair and Gas       1.0    1,250.00    1,250.00  02/07/2026
21                     Iron Rod(10mm))     250.0      330.00   82,500.00  02/08/2026
22                       Iron Rod(6mm)     200.0      130.00   26,000.00  02/08/2026
23                        Binding Wire       3.0      500.00    1,500.00  02/08/2026
24                 Materials Transport       1.0    1,800.00    1,800.00  02/08/2026
25            Contractor Njaye Payment       1.0  100,000.00  100,000.00  02/09/2026
26               Ali Packing the Woods       1.0    2,000.00    2,000.00  02/09/2026
27                            Nail(kg)       7.0      101.00      707.00  02/12/2026
28                       Sand(10wheel)       1.0    8,000.00    8,000.00  02/13/2026
29            Generator Repair and Gas       1.0    1,900.00    1,900.00  02/14/2026
30                              Cement      50.0      450.00   22,500.00  02/18/2026
31                   Cement Transport       50.0       20.00    1,000.00  02/18/2026
32                            2/5 Wood       4.0      325.00    1,300.00  02/18/2026
33                 1/5 Wood Transport        4.0      100.00      400.00  02/18/2026
34                  Gas for Generator        1.0      450.00      450.00  02/21/2026
35                Ramadan Experiences        1.0    6,000.00    6,000.00  03/26/2026
36                            Nail(kg)       9.0      100.00      900.00  03/02/2026
37                            1/2 Wood      15.0      120.00    1,800.00  03/02/2026
38                 Materials Transport       1.0      300.00      300.00  03/02/2026
39                              Cement      50.0      450.00   22,500.00  03/03/2026
40                   Cement Transport       50.0       22.00    1,100.00  03/03/2026
41                       Sand(10wheel)       1.0    8,000.00    8,000.00  03/03/2026
42                  Gas for Generator        1.0      400.00      400.00  03/06/2026
43                        Ali’ Salary        1.0    5,500.00    5,500.00  03/06/2026
44                              Cement      25.0      450.00   11,250.00  03/13/2026
45                   Cement Transport       25.0       20.00      500.00  03/13/2026
46                  Gas for Generator        1.0      400.00      400.00  03/13/2026
47                     Design Pillars        6.0    1,500.00    9,000.00  03/15/2026
48            Contractor Njaye Payment       1.0   20,000.00   20,000.00  03/17/2026
49                 Oil for Big Pillars       1.0      140.00      140.00  03/17/2026
50                              Cement      25.0      450.00   11,250.00  03/17/2026
51                   Cement Transport       25.0       20.00      500.00  03/17/2026
52      Big Pillar Mold  Rental (days)       3.0    1,000.00    3,000.00  03/19/2026
53          Big Pillar Mold Transport        1.0    1,000.00    1,000.00  03/19/2026
54                Cardboard and nails        1.0      700.00      700.00  03/26/2026
55                           1/5 Wood        5.0      350.00    1,750.00  03/28/2026
56                 1/5 Wood Transport        1.0      400.00      400.00  03/28/2026
57                  Gas for Generator        1.0      400.00      400.00  03/28/2026
58       Bubacarr Faye Court Expenses        1.0    1,000.00    1,000.00  03/29/2026
59    Scaffolding Rental, Safo (Daily)       6.0      150.00      900.00  03/30/2026
60               Scaffolding Transport       2.0      200.00      400.00  03/30/2026
61                            Nail(kg)       2.0      100.00      200.00  03/30/2026
62                        Ali’ Salary        1.0    5,500.00    5,500.00  04/01/2026
63                   Ackro Jack Rental       6.0       25.00      150.00  04/11/2026
64    Scaffolding Rental, Safo (Daily)       1.0    1,200.00    1,200.00  04/11/2026
65                            1/2 Wood       2.0      120.00      240.00  04/11/2026
66                 Material Transport        1.0      500.00      500.00  04/11/2026
67      Big Pillar Mold  Rental (days)       1.0    1,000.00    1,000.00  04/14/2026
68          Big Pillar Mold Transport        2.0      300.00      600.00  04/14/2026
69            Contractor Njaye Payment       1.0   50,000.00   50,000.00  04/20/2026
70        Residual - for Bubacarr Faye       1.0      647.00      647.00  04/29/2026

In [40]:
thirdfloor_const.to_csv('ParadiseView/out/df_thirdfloor_const.csv', index=False)

In [43]:
thirdfloor_const = pd.read_csv('ParadiseView/out/df_thirdfloor_const.csv')

In [44]:
thirdfloor_const['date'] = pd.to_datetime(thirdfloor_const['date'])

In [45]:
thirdfloor_const.head()

                       item  quantity   unit_cost  total_cost       date
0                    Cement      36.0      480.00   17,280.00 2026-12-29
1         Cement Transport       36.0       20.00      720.00 2026-12-29
2             Sand(10wheel)       1.0    8,000.00    8,000.00 2026-12-29
3  Contractor Njaye Payment       1.0  100,000.00  100,000.00 2026-01-20
4            Iron Rod(12mm)     103.0      540.00   55,620.00 2026-01-22

In [128]:
thirdfloor_const['exchange_rate'] = np.where(thirdfloor_const['date'] == '2026-12-29', 74.00, 0.00)

In [129]:
thirdfloor_const['exchange_rate'] = np.where(thirdfloor_const['date'].between('2026-01-20', '2026-01-24'), 73.50, thirdfloor_const['exchange_rate'])

In [130]:
thirdfloor_const['exchange_rate'] = np.where(thirdfloor_const['date'].between('2026-01-25', '2026-04-29'), 73.75, thirdfloor_const['exchange_rate'])

In [131]:
thirdfloor_const['sub_category'] = 'Construction'
thirdfloor_const['category'] = '3rd Floor'

In [132]:
thirdfloor_const['unit_cost'] = thirdfloor_const['unit_cost'].str.replace(',', '').astype('float64')

AttributeError: Can only use .str accessor with string values, not floating

In [85]:
thirdfloor_const['total_cost'] = thirdfloor_const['total_cost'].str.replace(',', '').astype('float64')

In [126]:
thirdfloor_const = thirdfloor_const.reindex(columns=['item', 'quantity', 'unit_cost', 'total_cost', 'date', 'sub_category', 'category', 'exchange_rate'])

In [90]:
thirdfloor_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   item          71 non-null     str
 1   quantity      71 non-null     float64
 2   unit_cost     71 non-null     float64
 3   total_cost    71 non-null     float64
 4   date          71 non-null     datetime64[us]
 5   sub_category  71 non-null     str
 6   category      71 non-null     str
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 4.0 KB

In [97]:
thirdfloor_const.at[63, 'item'] = 'Acrojack Rental'

In [103]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Nail(kg)', 'Nail (kg)', thirdfloor_const['item'])

In [107]:
thirdfloor_const[thirdfloor_const['item'] == 'Nail (kg)']

,item,quantity,unit_cost,total_cost,date,sub_category,category
18,Nail (kg),10.0,100.0,1000.0,2026-01-31,Construction,3rd Floor
27,Nail (kg),7.0,101.0,707.0,2026-02-12,Construction,3rd Floor
36,Nail (kg),9.0,100.0,900.0,2026-03-02,Construction,3rd Floor
61,Nail (kg),2.0,100.0,200.0,2026-03-30,Construction,3rd Floor

In [111]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Sand(10wheel)', 'Sand (10 Wheel)', thirdfloor_const['item'])

In [115]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Asphalt(95cu)', 'Asphalt (95cu)', thirdfloor_const['item'])

In [119]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Iron Rod(10mm))', 'Iron Rod (10mm)', thirdfloor_const['item'])

In [122]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Iron Rod(12mm)', 'Iron Rod (12mm)', thirdfloor_const['item'])

In [123]:
thirdfloor_const['item'] = np.where(thirdfloor_const['item'] == 'Iron Rod(6mm)', 'Iron Rod (6mm)', thirdfloor_const['item'])

In [135]:
dollar = thirdfloor_const['total_cost'] / thirdfloor_const['exchange_rate']

In [137]:
dollar.sum()

np.float64(12557.135785803097)

In [133]:
print(thirdfloor_const.to_string())

                                  item  quantity  unit_cost  total_cost       date  sub_category   category  exchange_rate
0                               Cement      36.0      480.0     17280.0 2026-12-29  Construction  3rd Floor          74.00
1                    Cement Transport       36.0       20.0       720.0 2026-12-29  Construction  3rd Floor          74.00
2                      Sand (10 Wheel)       1.0     8000.0      8000.0 2026-12-29  Construction  3rd Floor          74.00
3             Contractor Njaye Payment       1.0   100000.0    100000.0 2026-01-20  Construction  3rd Floor          73.50
4                      Iron Rod (12mm)     103.0      540.0     55620.0 2026-01-22  Construction  3rd Floor          73.50
5                         Binding Wire       1.0      500.0       500.0 2026-01-22  Construction  3rd Floor          73.50
6   Iron Rod + Binding Wite Transport        1.0      700.0       700.0 2026-01-22  Construction  3rd Floor          73.50
7                  Big Plastic Barrel        2.0     1000.0      2000.0 2026-01-23  Construction  3rd Floor          73.50
8                   Barrels Transport        1.0      500.0       500.0 2026-01-23  Construction  3rd Floor          73.50
9                   Gas for Generator        1.0      475.0       475.0 2026-01-23  Construction  3rd Floor          73.50
10               Bubacarr Faye Payment       1.0    60000.0     60000.0 2026-01-24  Construction  3rd Floor          73.50
11                              Cement     100.0      465.0     46500.0 2026-01-27  Construction  3rd Floor          73.75
12                   Cement Transport      100.0       20.0      2000.0 2026-01-27  Construction  3rd Floor          73.75
13                     Sand (10 Wheel)       1.0     8000.0      8000.0 2026-01-27  Construction  3rd Floor          73.75
14            Contractor Njaye Payment       1.0   100000.0    100000.0 2026-01-28  Construction  3rd Floor          73.75
15             Fixing Momo Haja’s Gate       1.0      700.0       700.0 2026-01-29  Construction  3rd Floor          73.75
16                  Gas for Generator        1.0      500.0       500.0 2026-01-30  Construction  3rd Floor          73.75
17                      Asphalt (95cu)       1.0    95000.0     95000.0 2026-01-31  Construction  3rd Floor          73.75
18                           Nail (kg)      10.0      100.0      1000.0 2026-01-31  Construction  3rd Floor          73.75
19                       Ali’ Payment        1.0     5500.0      5500.0 2026-02-04  Construction  3rd Floor          73.75
20            Generator Repair and Gas       1.0     1250.0      1250.0 2026-02-07  Construction  3rd Floor          73.75
21                     Iron Rod (10mm)     250.0      330.0     82500.0 2026-02-08  Construction  3rd Floor          73.75
22                      Iron Rod (6mm)     200.0      130.0     26000.0 2026-02-08  Construction  3rd Floor          73.75
23                        Binding Wire       3.0      500.0      1500.0 2026-02-08  Construction  3rd Floor          73.75
24                 Materials Transport       1.0     1800.0      1800.0 2026-02-08  Construction  3rd Floor          73.75
25            Contractor Njaye Payment       1.0   100000.0    100000.0 2026-02-09  Construction  3rd Floor          73.75
26               Ali Packing the Woods       1.0     2000.0      2000.0 2026-02-09  Construction  3rd Floor          73.75
27                           Nail (kg)       7.0      101.0       707.0 2026-02-12  Construction  3rd Floor          73.75
28                     Sand (10 Wheel)       1.0     8000.0      8000.0 2026-02-13  Construction  3rd Floor          73.75
29            Generator Repair and Gas       1.0     1900.0      1900.0 2026-02-14  Construction  3rd Floor          73.75
30                              Cement      50.0      450.0     22500.0 2026-02-18  Construction  3rd Floor          73.75
31                   Cement Transport       50.0       20.0      1000.0 2026-02-18  Construction  3rd Floor          73.75
32                            2/5 Wood       4.0      325.0      1300.0 2026-02-18  Construction  3rd Floor          73.75
33                 1/5 Wood Transport        4.0      100.0       400.0 2026-02-18  Construction  3rd Floor          73.75
34                  Gas for Generator        1.0      450.0       450.0 2026-02-21  Construction  3rd Floor          73.75
35                Ramadan Experiences        1.0     6000.0      6000.0 2026-03-26  Construction  3rd Floor          73.75
36                           Nail (kg)       9.0      100.0       900.0 2026-03-02  Construction  3rd Floor          73.75
37                            1/2 Wood      15.0      120.0      1800.0 2026-03-02  Construction  3rd Floor          73.75
38                 Materials Transport       1.0      300.0       300.0 2026-03-02  Construction  3rd Floor          73.75
39                              Cement      50.0      450.0     22500.0 2026-03-03  Construction  3rd Floor          73.75
40                   Cement Transport       50.0       22.0      1100.0 2026-03-03  Construction  3rd Floor          73.75
41                     Sand (10 Wheel)       1.0     8000.0      8000.0 2026-03-03  Construction  3rd Floor          73.75
42                  Gas for Generator        1.0      400.0       400.0 2026-03-06  Construction  3rd Floor          73.75
43                        Ali’ Salary        1.0     5500.0      5500.0 2026-03-06  Construction  3rd Floor          73.75
44                              Cement      25.0      450.0     11250.0 2026-03-13  Construction  3rd Floor          73.75
45                   Cement Transport       25.0       20.0       500.0 2026-03-13  Construction  3rd Floor          73.75
46                  Gas for Generator        1.0      400.0       400.0 2026-03-13  Construction  3rd Floor          73.75
47                     Design Pillars        6.0     1500.0      9000.0 2026-03-15  Construction  3rd Floor          73.75
48            Contractor Njaye Payment       1.0    20000.0     20000.0 2026-03-17  Construction  3rd Floor          73.75
49                 Oil for Big Pillars       1.0      140.0       140.0 2026-03-17  Construction  3rd Floor          73.75
50                              Cement      25.0      450.0     11250.0 2026-03-17  Construction  3rd Floor          73.75
51                   Cement Transport       25.0       20.0       500.0 2026-03-17  Construction  3rd Floor          73.75
52      Big Pillar Mold  Rental (days)       3.0     1000.0      3000.0 2026-03-19  Construction  3rd Floor          73.75
53          Big Pillar Mold Transport        1.0     1000.0      1000.0 2026-03-19  Construction  3rd Floor          73.75
54                Cardboard and nails        1.0      700.0       700.0 2026-03-26  Construction  3rd Floor          73.75
55                           1/5 Wood        5.0      350.0      1750.0 2026-03-28  Construction  3rd Floor          73.75
56                 1/5 Wood Transport        1.0      400.0       400.0 2026-03-28  Construction  3rd Floor          73.75
57                  Gas for Generator        1.0      400.0       400.0 2026-03-28  Construction  3rd Floor          73.75
58       Bubacarr Faye Court Expenses        1.0     1000.0      1000.0 2026-03-29  Construction  3rd Floor          73.75
59    Scaffolding Rental, Safo (Daily)       6.0      150.0       900.0 2026-03-30  Construction  3rd Floor          73.75
60               Scaffolding Transport       2.0      200.0       400.0 2026-03-30  Construction  3rd Floor          73.75
61                           Nail (kg)       2.0      100.0       200.0 2026-03-30  Construction  3rd Floor          73.75
62                        Ali’ Salary        1.0     5500.0      5500.0 2026-04-01  Construction  3rd Floor          73.75
63                     Acrojack Rental       6.0       25.0       150.0 2026-04-11  Construction  3rd Floor          73.75
64    Scaffolding Rental, Safo (Daily)       1.0     1200.0      1200.0 2026-04-11  Construction  3rd Floor          73.75
65                            1/2 Wood       2.0      120.0       240.0 2026-04-11  Construction  3rd Floor          73.75
66                 Material Transport        1.0      500.0       500.0 2026-04-11  Construction  3rd Floor          73.75
67      Big Pillar Mold  Rental (days)       1.0     1000.0      1000.0 2026-04-14  Construction  3rd Floor          73.75
68          Big Pillar Mold Transport        2.0      300.0       600.0 2026-04-14  Construction  3rd Floor          73.75
69            Contractor Njaye Payment       1.0    50000.0     50000.0 2026-04-20  Construction  3rd Floor          73.75
70        Residual - for Bubacarr Faye       1.0      647.0       647.0 2026-04-29  Construction  3rd Floor          73.75

In [138]:
thirdfloor_const.to_csv('ParadiseView/out/df_thirdfloor_const.csv', index=False)

In [139]:
pd.read_csv('ParadiseView/out/df_thirdfloor_const.csv')

,item,quantity,unit_cost,total_cost,date,sub_category,category,exchange_rate
0,Cement,36.0,480.0,17280.0,2026-12-29,Construction,3rd Floor,74.00
1,Cement Transport,36.0,20.0,720.0,2026-12-29,Construction,3rd Floor,74.00
2,Sand (10 Wheel),1.0,8000.0,8000.0,2026-12-29,Construction,3rd Floor,74.00
3,Contractor Njaye Payment,1.0,100000.0,100000.0,2026-01-20,Construction,3rd Floor,73.50
4,Iron Rod (12mm),103.0,540.0,55620.0,2026-01-22,Construction,3rd Floor,73.50
...,...,...,...,...,...,...,...,...
66,Material Transport,1.0,500.0,500.0,2026-04-11,Construction,3rd Floor,73.75
67,Big Pillar Mold Rental (days),1.0,1000.0,1000.0,2026-04-14,Construction,3rd Floor,73.75
68,Big Pillar Mold Transport,2.0,300.0,600.0,2026-04-14,Construction,3rd Floor,73.75
69,Contractor Njaye Payment,1.0,50000.0,50000.0,2026-04-20,Construction,3rd Floor,73.75
70,Residual - for Bubacarr Faye,1.0,647.0,647.0,2026-04-29,Construction,3rd Floor,73.75